# SPDX-FileCopyrightText: 2025 Ferdinand Thiessen
# SPDX-License-Identifier: MIT

name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-dev-engines:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          path: ./tests/fixtures/dev-engines-only.json

      - name: Check Output
        run: |
          [ "${{ steps.test-action.outputs.node-version }}" = ">=16.0.0" ] && \
          [ "${{ steps.test-action.outputs.package-manager-name }}" = "yarn" ] && \
          [ "${{ steps.test-action.outputs.package-manager-version }}" = ">=2.0.0" ]
